# Generated by Django 5.2.9 on 2026-01-12 07:53

import django.db.models.deletion
import django.utils.timezone
import master_apps.principle_employee.models
import master_apps.principle_employee.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('ho_address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('nature_of_business', models.CharField(max_length=100)),
                ('establishment_type', models.CharField(max_length=100)),
                ('rules_applicable', models.CharField(choices=[('central', 'Central'), ('state', 'State')], max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalEmployerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=master_apps.principle_employee.models.pe_document_upload_path, validators=[master_apps.principle_employee.validators.validate_document_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('principal_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='principle_employee.principalemployer')),
            ],
        ),
    ]
