# Generated by Django 5.2.9 on 2026-03-05 07:52

import django.db.models.deletion
import master_apps.principle_employee.models
import master_apps.principle_employee.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('ho_address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('nature_of_business', models.CharField(max_length=100)),
                ('establishment_type', models.CharField(max_length=100)),
                ('rules_applicable', models.CharField(choices=[('central', 'Central'), ('state', 'State')], max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principalemployer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalEmployerBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='principal_employer_branches/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('principal_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='principle_employee.principalemployer')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalEmployerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=master_apps.principle_employee.models.pe_document_upload_path, validators=[master_apps.principle_employee.validators.validate_document_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('principal_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='principle_employee.principalemployer')),
            ],
        ),
    ]
