# Generated by Django 5.2.9 on 2026-04-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalemployer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
