# Generated by Django 5.2.9 on 2026-02-27 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='principalemployer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pe_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='principalemployer',
            name='start_date',
            field=models.DateField(),
        ),
    ]
