# Generated by Django 5.2.9 on 2026-07-31 08:03

import django.db.models.deletion
import master_apps.principle_employee.models
import master_apps.principle_employee.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_employee', '0002_principalemployer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalEmployerBranchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=master_apps.principle_employee.models.branch_document_upload_path, validators=[master_apps.principle_employee.validators.validate_document_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='principle_employee.principalemployerbranch')),
            ],
        ),
    ]
