# Generated by Django 5.2.9 on 2026-03-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_employee', '0003_alter_principalemployer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalEmployerBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('principal_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='principle_employee.principalemployer')),
            ],
        ),
    ]
