# Generated by Django 5.2.9 on 2026-03-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_employee', '0004_principalemployerbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalemployerbranch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
