# Generated by Django 5.2.9 on 2026-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_employee', '0005_principalemployerbranch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalemployerbranch',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='branch_documents/'),
        ),
    ]
