# Generated by Django 5.2.9 on 2026-03-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_employee', '0006_principalemployerbranch_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalemployerbranch',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='principal_employer_branches/'),
        ),
    ]
