# Generated by Django 5.2.9 on 2026-04-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_auditor_user'),
        ('checklist', '0004_alter_auditchecklist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField()),
                ('audit_period', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('observation', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='auditor.auditor')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.auditchecklist')),
            ],
        ),
    ]
