# Generated by Django 5.2.9 on 2026-04-22 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_auditentry'),
        ('checklist', '0004_alter_auditchecklist_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='status',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not Applicable', 'Not Applicable'), ('Delayed Complied', 'Delayed Complied')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='auditentry',
            unique_together={('checklist', 'branch_id', 'audit_period')},
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['branch_id', 'audit_period'], name='auditor_aud_branch__0d61d5_idx'),
        ),
    ]
