# Generated by Django 5.2.9 on 2026-04-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0004_auditentry_submitted_by_alter_auditentry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='status',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not Complied', 'Not Complied'), ('Not Applicable', 'Not Applicable'), ('Not Applicable For Audit Period', 'Not Applicable For Audit Period'), ('Delayed Complied', 'Delayed Complied'), ('Exceptional Approval - Delayed Complied', 'Exceptional Approval - Delayed Complied'), ('Exceptional Approval- Not Complied', 'Exceptional Approval- Not Complied'), ('Incorrect Document Submitted', 'Incorrect Document Submitted')], max_length=50),
        ),
    ]
