# Generated by Django 5.2.9 on 2026-12-15 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0005_alter_auditentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField()),
                ('audit_period', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FROZEN', 'Frozen')], default='DRAFT', max_length=20)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditor.auditor')),
            ],
            options={
                'unique_together': {('auditor', 'branch_id', 'audit_period')},
            },
        ),
    ]
