# Generated by Django 5.2.9 on 2026-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0006_auditsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='show_auditor_guidelines',
            field=models.BooleanField(default=True),
        ),
    ]
