# Generated by Django 5.2.9 on 2026-07-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0007_auditor_show_auditor_guidelines'),
        ('vendor', '0030_vendorcompliancepayroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='vendor.vendorcompliancesubmission'),
        ),
    ]
