# Generated by Django 5.2.9 on 2026-03-07 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('principle_employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmaster',
            name='principal_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principle_employee.principalemployer'),
        ),
        migrations.AlterField(
            model_name='documentmaster',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
