# Generated by Django 5.2.9 on 2026-03-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentmaster_principal_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmaster',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=20),
        ),
    ]
