# Generated by Django 5.2.9 on 2026-04-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentmaster_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('audit_period', models.CharField(max_length=100)),
                ('main_file', models.FileField(upload_to='compliance/main/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('branch_id', models.IntegerField()),
                ('document_id', models.IntegerField()),
            ],
            options={
                'db_table': 'audit_submission',
                'managed': False,
            },
        ),
    ]
