# Generated by Django 5.2.9 on 2026-04-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auditsubmission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditsubmission',
            table='compliance_submission',
        ),
    ]
