# Generated by Django 5.2.9 on 2026-05-13 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_auditsubmission_table'),
        ('vendor', '0017_vendorcompliancesubmission_clearance_email_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAuditArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_type', models.CharField(choices=[('CC_PDF', 'CC PDF'), ('CLEARANCE_EMAIL', 'Clearance Email'), ('FREEZE_REPORT', 'Freeze Report'), ('EXCEPTIONAL_APPROVAL', 'Exceptional Approval')], max_length=50)),
                ('file', models.FileField(upload_to='compliance/archive/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_archives', to='vendor.vendorcompliancesubmission')),
            ],
            options={
                'db_table': 'compliance_audit_archive',
                'ordering': ['-created_at'],
            },
        ),
    ]
