# Generated by Django 5.2.9 on 2026-12-15 06:01

import master_apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_complianceauditarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceauditarchive',
            name='file',
            field=models.FileField(upload_to=master_apps.documents.models.compliance_archive_upload_path),
        ),
    ]
