# Generated by Django 5.2.9 on 2026-05-16 09:47

import master_apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_complianceauditarchive_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceauditarchive',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=master_apps.documents.models.compliance_archive_upload_path),
        ),
    ]
