# Generated by Django 5.2.9 on 2026-05-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_complianceauditarchive_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceauditarchive',
            name='archive_type',
            field=models.CharField(choices=[('CC_PDF', 'CC PDF'), ('FREEZE_REPORT', 'Freeze Report'), ('EXCEPTIONAL_APPROVAL', 'Exceptional Approval')], max_length=50),
        ),
    ]
