# Generated by Django 5.2.9 on 2026-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_complianceauditarchive_archive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmaster',
            name='document_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
