# Generated by Django 5.2.9 on 2026-01-12 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('act_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_central_act', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.act')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.section')),
            ],
        ),
        migrations.CreateModel(
            name='AuditChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_guide', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklist.act')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentmaster')),
                ('compliance_nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklist.compliancenature')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklist.rule')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklist.section')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklist.state')),
            ],
        ),
        migrations.CreateModel(
            name='StateAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.act')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.state')),
            ],
            options={
                'unique_together': {('state', 'act')},
            },
        ),
    ]
