# Generated by Django 5.2.9 on 2026-03-22 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        ('documents', '0003_alter_documentmaster_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchecklist',
            name='jurisdiction',
            field=models.CharField(choices=[('STATE', 'State'), ('CENTRAL', 'Central')], default='STATE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditchecklist',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.rule'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('section', 'rule_number')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('act', 'section_number')},
        ),
        migrations.AddIndex(
            model_name='auditchecklist',
            index=models.Index(fields=['state', 'act'], name='checklist_a_state_i_e2c5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditchecklist',
            index=models.Index(fields=['is_active'], name='checklist_a_is_acti_6ae3c4_idx'),
        ),
    ]
