# Generated by Django 5.2.9 on 2026-03-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auditchecklist_jurisdiction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditchecklist',
            name='jurisdiction',
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='audit_particulars',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='form_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
