# Generated by Django 5.2.9 on 2026-04-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_remove_auditchecklist_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditchecklist',
            options={'ordering': ['state', 'act', 'section']},
        ),
    ]
