# Generated by Django 5.2.9 on 2026-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_alter_auditchecklist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditchecklist',
            options={'ordering': ['state', 'act', 'section', 'sequence']},
        ),
        migrations.AddField(
            model_name='auditchecklist',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
