# Generated by Django 5.2.9 on 2026-10-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_auditchecklist_options_auditchecklist_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditchecklist',
            name='check_group',
            field=models.CharField(default='First Check', max_length=100),
        ),
    ]
