# Generated by Django 5.2.9 on 2025-12-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_used',
            field=models.BooleanField(default=False),
        ),
    ]
