# Generated by Django 5.2.9 on 2025-12-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_reset_password_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superadmin',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('PE', 'Principal Employer'), ('VENDOR', 'Vendor'), ('AUDITOR', 'Auditor')], default='PE', max_length=20),
        ),
    ]
