# Generated by Django 5.2.9 on 2026-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_mobile_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
